multiple_response_mock = [{'average_rating': 3.5,
           'event_id': 1,
           'event_image': 'https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png',
           'event_name': 'ECE444 project UX help session',
           'event_time': 'Mon, 04 Nov 2024 14:00:00 GMT',
           'filter_info': ['art']},
          {'average_rating': 3.5,
           'event_id': 2,
           'event_image': 'https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png',
           'event_name': 'ECE444 project UX help session 2',
           'event_time': 'Sat, 04 Nov 2023 14:00:00 GMT',
           'filter_info': ['art']},
          {'average_rating': 3.5,
           'event_id': 3,
           'event_image': 'https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png',
           'event_name': 'ECE444 project UX help session 3',
           'event_time': 'Sun, 05 Nov 2023 14:00:00 GMT',
           'filter_info': ['art']},
          {'average_rating': 3.5,
           'event_id': 4,
           'event_image': 'https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png',
           'event_name': 'ECE444 project UX help session 4',
           'event_time': 'Mon, 06 Nov 2023 14:00:00 GMT',
           'filter_info': ['art']},
          {'average_rating': 3.5,
           'event_id': 5,
           'event_image': 'https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png',
           'event_name': 'ECE444 project UX help session 5',
           'event_time': 'Tue, 07 Nov 2023 14:00:00 GMT',
           'filter_info': ['art']}]


single_response_mock = [{'average_rating': 3.5,
           'event_id': 6,
           'event_image': 'https://images.pexels.com/photos/1045534/pexels-photo-1045534.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
           'event_name': 'Montreal Basketball League Tryout',
           'event_time': 'Tue, 07 Nov 2023 14:00:00 GMT',
           'filter_info': ['sport', 'travel']}]

request_with_whitespace_mock = [{'average_rating': 3.5,
           'event_id': 6,
           'event_image': 'https://images.pexels.com/photos/1045534/pexels-photo-1045534.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
           'event_name': 'Montreal Basketball League Tryout',
           'event_time': 'Tue, 07 Nov 2023 14:00:00 GMT',
           'filter_info': ['sport', 'travel']}]

