from datetime import datetime

event_info_model_mock_data = [
    {
        "event_name": "ECE444 project UX help session",
        "event_time": datetime(2024, 11, 4, 14, 0, 0),
        "number_rater": "3",
        "average_rating": 3.5,
        "event_description": "help student with ECE444 project and have a secret party",
        "club_id": '2',
        "event_image": 'https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png',
        "position_address": "Exam Center",
        "address": "777 Bay ST."
    },
    {
        "event_name": "ECE444 project UX help session 2",
        "event_time": datetime(2023, 11, 4, 14, 0, 0),
        "number_rater": "3",
        "average_rating": 3.5,
        "event_description": "help student with ECE444 project and have a secret party",
        "club_id": '2',
        "event_image": 'https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png',
        "position_address": "Exam Center",
        "address": "777 Bay ST."
    },
    {
        "event_name": "ECE444 project UX help session 3",
        "event_time": datetime(2023, 11, 5, 14, 0, 0),
        "number_rater": "3",
        "average_rating": 3.5,
        "event_description": "help student with ECE444 project and have a secret party",
        "club_id": '2',
        "event_image": 'https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png',
        "position_address": "Exam Center",
        "address": "777 Bay ST."
    },
    {
        "event_name": "ECE444 project UX help session 4",
        "event_time": datetime(2023, 11, 6, 14, 0, 0),
        "number_rater": "3",
        "average_rating": 3.5,
        "event_description": "help student with ECE444 project and have a secret party",
        "club_id": '2',
        "event_image": 'https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png',
        "position_address": "Exam Center",
        "address": "777 Bay ST.",
    },
    {
        "event_name": "ECE444 project UX help session 5",
        "event_time": datetime(2023, 11, 7, 14, 0, 0),
        "number_rater": "3",
        "average_rating": 3.5,
        "event_description": "help student with ECE444 project and have a secret party",
        "club_id": '2',
        "event_image": 'https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png',
        "position_address": "Exam Center",
        "address": "777 Bay ST.",
    },
    {
        "event_name": "Montreal Basketball League Tryout",
        "event_time": datetime(2023, 11, 7, 14, 0, 0),
        "number_rater": "3",
        "average_rating": 3.5,
        "event_description": "help student with ECE444 project and have a secret party",
        "club_id": '2',
        "event_image": 'https://images.pexels.com/photos/1045534/pexels-photo-1045534.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        "position_address": "Exam Center",
        "address": "777 Bay ST.",
    },
    {
        "event_name": "Cooking101",
        "event_time": datetime(2023, 11, 20, 14, 0, 0),
        "number_rater": "3",
        "average_rating": 4,
        "event_description": "For anyone who want to learn and free food",
        "club_id": '6',
        "event_image": 'https://th.bing.com/th/id/R.f54151e64a0634920de394b02d977025?rik=iUjPShv3uu2qMQ&pid=ImgRaw&r=0',
        "position_address": "SF Pit",
        "address": "10 King's College Road",
    },
    {
        "event_name": "Cooking is art",
        "event_time": datetime(2023, 11, 22, 14, 0, 0),
        "number_rater": "3",
        "average_rating": 4,
        "event_description": "Continuation of Cooking 101. Let's learn how to cook Thai food! Come and Join us!!!",
        "club_id": '6',
        "event_image": 'https://i.pinimg.com/originals/b9/ab/ee/b9abeeb416c0303f337b078fc015104b.jpg',
        "position_address": "SF Pit",
        "address": "10 King's College Road",
    },
    {
        "event_name": "Filming and CGI",
        "event_time": datetime(2023, 11, 30, 14, 0, 0),
        "number_rater": "2",
        "average_rating": 5,
        "event_description": "Excellent filming experiences with Mr.Jerry",
        "club_id": '7',
        "event_image": 'https://th.bing.com/th/id/OIP.xtzZpD9co7u3S6jU9J1ZPwHaE8?pid=ImgDet&rs=1',
        "position_address": "MY150",
        "address": "35 St.George St.",
    }
]
